using Task9;

Rational rational1 = new Rational(1, 5);
Console.WriteLine(rational1);
Rational rational2 = new Rational(2, 4);
Console.WriteLine(rational2);
Rational rational3 = new Rational(2, 6);
Console.WriteLine(rational3);
//Rational rational3 = new Rational(3, 0);
//Console.WriteLine(rational3);
Rational rational4 = new Rational(4, -8);
Console.WriteLine(rational4);
Rational rational5 = new Rational(-5, 11);
Console.WriteLine(rational5);
Rational rational6 = new Rational(-6, -19);
Console.WriteLine(rational6);
Rational rational7 = new Rational(-6, 3);
Console.WriteLine(rational7);
Rational rational8 = new Rational(1, 2);
Console.WriteLine(rational8);
Console.WriteLine(rational2.Equals(rational8));
Console.WriteLine(rational2.Equals(rational4));
Console.WriteLine(rational1.CompareTo(null));
Console.WriteLine(rational2.CompareTo(rational8));
Console.WriteLine(rational1.CompareTo(rational2));
Console.WriteLine(rational1.CompareTo(rational4));
Console.WriteLine(rational1 + rational6);
Console.WriteLine(rational1 - rational6);
Console.WriteLine(rational1 * rational6);
Console.WriteLine(rational1 / rational6);
Console.WriteLine((double)rational6);
Rational rational9 = 5;
Console.WriteLine(rational9);